[versions]
jbCompose = "1.5.1"
koin = "3.5.0"
kool = "0.11.0"     # "0.12.1-SNAPSHOT" - newer but minor breaking changes might occur from time to time
kotest = "5.7.2"
kotlin = "1.9.10"
kotlinxCoroutines = "1.7.3"   # kool has 1.7.1 - we'll see
kotlinxDatetime = "0.4.1"
kotlinxSerialization = "1.6.0"
ktor = "2.3.4"


[libraries]

# Koin
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin"}
koin-core-js = { module = "io.insert-koin:koin-core-js", version.ref = "koin"}
koin-core-jvm = { module = "io.insert-koin:koin-core-jvm", version.ref = "koin"}
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin"}
koin-test-junit5 = { module = "io.insert-koin:koin-test-junit5", version.ref = "koin"}

# Kool
kool-core = { module = "de.fabmax.kool:kool-core", version.ref = "kool"}
kool-physics = { module = "de.fabmax.kool:kool-physics", version.ref = "kool"}

# Kotest
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-framework-datatest = { module = "io.kotest:kotest-framework-datatest", version.ref = "kotest" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-framework-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }

# Kotlin
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

# Ktor
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }


[plugins]
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jbCompose" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotest-multiplatform = { id = "io.kotest.multiplatform", version.ref = "kotest" }
